# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia',
            name='verify',
            field=models.BooleanField(default=True, verbose_name='Verify'),
        ),
    ]
