# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170617_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=255, verbose_name='Recipient ID')),
            ],
            options={
                'verbose_name_plural': 'User Facebook',
            },
        ),
    ]
