# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20170617_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacebook',
            name='text',
            field=models.CharField(default='q', max_length=255, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfacebook',
            name='sender_id',
            field=models.CharField(max_length=255, verbose_name='Sender ID'),
        ),
    ]
