# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20170617_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacebook',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
    ]
