# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_facebook_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='payload',
            field=models.BooleanField(default=False, verbose_name='Payload'),
        ),
    ]
