# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_facebook_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='payload',
        ),
        migrations.AddField(
            model_name='ia',
            name='payload',
            field=models.BooleanField(default=False, verbose_name='Payload'),
        ),
    ]
